feat: pause contract
linear-protocol/LiNEAR pull request #121
Opened 2022-11-03 09:13 UTC by dongcool

2022-11-04 10:58 UTC, linguists requested changes

2022-11-04 10:58 UTC, linguists commented on contracts/linear/src/owner.rs
> +        self.assert_owner();
may assert contract is not paused:

```rust
require!(!self.paused, "The contract is already paused")
```

2022-11-04 10:58 UTC, linguists commented on contracts/linear/src/owner.rs
> +        self.assert_owner();
may assert contract has been paused:

```rust
require!(self.paused, "The contract is not paused")
```

2022-11-08 06:56 UTC, linguists requested changes

2022-11-08 06:56 UTC, linguists commented on contracts/linear/src/errors.rs
> +pub const ERR_PAUSED: &str = "The contract is paused now, please try later";
```suggestion
pub const ERR_PAUSED: &str = "The contract is paused now. Please try later";
```

2022-11-08 07:39 UTC, linguists commented on tests/__tests__/linear/pause.ava.ts
> +  );
Should we also test `stake` and `unstake` here?

2022-11-08 08:47 UTC, merged

2022-11-08 08:48 UTC, 0xdefacto approved these changes