feat: make sync balance public
linear-protocol/LiNEAR pull request #195
Opened 2024-03-26 03:10 UTC by dongcool

2025-04-17 08:33 UTC, linguists requested changes

2025-04-17 08:33 UTC, linguists commented on contracts/linear/src/epoch_actions.rs
>      pub fn validator_get_account_callback(
The `post_action` param can be removed from the function comment.

2025-04-18 03:32 UTC, arkff202310 approved these changes

2025-04-18 03:55 UTC, linguists approved these changes

2025-04-18 07:08 UTC, merged